### ISSUE TITLE
list_device throws AttributeError: type object 'UbloxGps' has no attribute 'available_addresses'

### ISSUE THREAD

**Issue by PorcelainMouse** [sparkfun/Qwiic_Py#8] opened 2020-09-23 06:50 UTC
Is this expected?  Perhaps for unsupported devices?

I have a fresh install of Raspbian, seems to work well. I followed the tutorial to turn the qwiic pHat button into a reset/shutdown switch, and that sort of works.  I also installed sparkfun_qwiic Python module & dependencies using pip.  I can import qwiic, but list_devices() fails with this error:

```
>>> results = qwiic.list_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/qwiic/__init__.py", line 270, in list_devices
    qwiic_devs = _QwiicInternal.get_available_devices()
  File "/home/pi/.local/lib/python3.7/site-packages/qwiic/__init__.py", line 136, in get_available_devices
    for addr in device_class.available_addresses:
AttributeError: type object 'UbloxGps' has no attribute 'available_addresses'
```
What's UbloxGps?  Should it always have this attribute, or is this a bug in list_device()?  This error does not occur without anything connected to the pHat, but always when either or both of the two sensors I have tried are attached.  I don't know what sensors are supported.  I have other sensors I can try, if that's helpful.

**Comment by santaimpersonator** [comment] 2020-10-08 19:12
I filed an issue for the error message. However, this issue is a duplicate of #2: https://github.com/sparkfun/Qwiic_Py/issues/2

- UbloxGps is a Python package linked to this package. The issue there is that package uses serial communication and not I2C which is why there is an error message. I have filed an issue (https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/issues/8) with the associated package.
- The `list.devices()` method is buggy and should not be used.

I will be closing this issue as the respective problems have been filed separately.

**Closed by santaimpersonator** 2020-10-08 19:12 UTC
Labels: duplicate
